/**
 * One valid record per table, used by the schema, export and import tests.
 * All content is original and fictional (CUR-15, SEC-03).
 */
import { DEFAULT_SETTINGS } from '../domain/settings.ts';
import type { RecordOf, TableName } from '../data/tables.ts';

export const T0 = Date.UTC(2026, 8, 27, 8, 0, 0);

const timestamps = { createdAt: T0, updatedAt: T0, deletedAt: null };

export const FIXTURE_IDS = {
  card: '4a1f0c7e-6a55-4d1e-9d2b-0f7c7a3b9e01',
  production: '4a1f0c7e-6a55-4d1e-9d2b-0f7c7a3b9e02',
  error: '4a1f0c7e-6a55-4d1e-9d2b-0f7c7a3b9e03',
  event: '4a1f0c7e-6a55-4d1e-9d2b-0f7c7a3b9e04',
  other: '4a1f0c7e-6a55-4d1e-9d2b-0f7c7a3b9e05',
} as const;

const srsState = {
  due: T0,
  stability: 0,
  difficulty: 0,
  scheduledDays: 0,
  learningSteps: 0,
  reps: 0,
  lapses: 0,
  phase: 'new',
  lastReview: null,
} as const;

export const VALID_RECORDS: { readonly [Name in TableName]: RecordOf<Name> } = {
  settings: { ...DEFAULT_SETTINGS, id: 'settings', ...timestamps, schemaVersion: 1 },
  notionProgress: {
    notionId: 'tense-just-already-yet-still',
    ...timestamps,
    schemaVersion: 1,
    status: 'in_progress',
    step: 2,
    recall: null,
    stepEnteredAt: T0,
    acquiredAt: null,
    lastRegressionAt: null,
  },
  exerciseAttempts: {
    id: FIXTURE_IDS.event,
    at: T0,
    schemaVersion: 1,
    exerciseId: 'tense-just-already-yet-still/s2/01',
    source: 'core',
    notionId: 'tense-just-already-yet-still',
    step: 2,
    answer: 'yet',
    result: 'correct',
    grader: 'local',
    hintUsed: false,
    context: 'path',
    durationMs: 4_000,
  },
  generatedExercises: {
    id: FIXTURE_IDS.other,
    ...timestamps,
    schemaVersion: 1,
    notionId: 'tense-past-simple',
    step: 3,
    exercise: {
      kind: 'fill-verb',
      sentence: 'She ___ the report on Monday.',
      verb: 'send',
      meaningFr: 'Elle a envoyé le rapport lundi.',
      accepted: ['sent'],
      knownErrors: ['sended'],
      explanation: 'Prétérit irrégulier : _send_, _sent_.',
    },
    model: 'claude-sonnet-5',
    promptVersion: 'generate-exercises@1',
    status: 'active',
  },
  cards: {
    id: FIXTURE_IDS.card,
    ...timestamps,
    schemaVersion: 1,
    content: {
      type: 'notion',
      notionId: 'tense-for-since-ago',
      meaningFr: 'Je travaille ici depuis trois ans.',
      hint: 'Durée qui continue jusqu’à maintenant.',
      answers: {
        canonical: 'I have worked here for three years.',
        variants: ['I have been working here for three years.'],
      },
    },
    notionId: 'tense-for-since-ago',
    sourceErrorId: null,
    status: 'active',
    suspensionReason: null,
    srs: srsState,
    due: T0,
    origin: 'notion',
  },
  reviewLogs: {
    id: FIXTURE_IDS.event,
    at: T0,
    schemaVersion: 1,
    cardId: FIXTURE_IDS.card,
    cardStatus: 'active',
    answer: 'I have worked here for three years.',
    hintUsed: false,
    result: 'correct',
    grader: 'local',
    grade: 'good',
    adjustedGrade: null,
    srsLog: {
      grade: 'good',
      phase: 'new',
      due: T0,
      stability: 2.3,
      difficulty: 2.1,
      scheduledDays: 0,
      learningSteps: 1,
      reviewedAt: T0,
    },
    durationMs: 9_000,
  },
  productions: {
    id: FIXTURE_IDS.production,
    ...timestamps,
    schemaVersion: 1,
    module: 'journal',
    prompt: { text: 'Raconte ta journée en trois phrases.', language: 'fr' },
    context: { notionId: null, itemId: null, tier: null, unstudied: false, hintUsed: false },
    // "Yesterday" is a finished time: the present perfect is wrong in every reading.
    text: 'Yesterday I have finished the quarterly report.',
    intentFr: "Hier, j'ai terminé le rapport trimestriel.",
    correction: null,
    result: null,
    grader: null,
    selfCorrections: null,
    durationMs: 60_000,
    status: 'submitted',
  },
  errors: {
    id: FIXTURE_IDS.error,
    ...timestamps,
    schemaVersion: 1,
    productionId: FIXTURE_IDS.production,
    index: 0,
    at: T0,
    category: 'temps_verbaux',
    notionId: 'tense-present-perfect-vs-past-simple',
    segment: { text: 'have finished', range: { start: 12, end: 25 } },
    correction: 'finished',
    rule: 'Moment passé précis : prétérit.',
    severity: 'medium',
    confidence: 'high',
    diagnosis: 'lapsus',
    confirmedByUser: false,
    reported: false,
  },
  lexicon: {
    id: FIXTURE_IDS.other,
    ...timestamps,
    schemaVersion: 1,
    key: 'meet a deadline',
    expression: 'meet a deadline',
    meaningFr: 'respecter une échéance',
    example: 'We met the deadline despite the audit.',
    source: 'manual',
    cardId: null,
  },
  ruleNotes: {
    category: 'prepositions',
    ...timestamps,
    schemaVersion: 1,
    note: 'depend on, interested in',
  },
  activity: {
    id: FIXTURE_IDS.event,
    at: T0,
    schemaVersion: 1,
    day: '2026-09-27',
    module: 'review',
    seconds: 300,
  },
  levelEstimates: {
    id: FIXTURE_IDS.event,
    at: T0,
    schemaVersion: 1,
    skill: 'writing',
    value: 2.5,
    displayed: 2.5,
    source: 'local',
    justification: null,
  },
  reports: {
    id: FIXTURE_IDS.other,
    ...timestamps,
    schemaVersion: 1,
    targetType: 'error',
    targetId: FIXTURE_IDS.error,
    reason: 'false-positive',
    comment: '',
    status: 'open',
  },
  diagnosticRuns: {
    id: FIXTURE_IDS.other,
    ...timestamps,
    schemaVersion: 1,
    step: 'placement',
    answers: [],
    result: null,
  },
  pronunciationAttempts: {
    id: FIXTURE_IDS.event,
    at: T0,
    schemaVersion: 1,
    expectedText: 'I think three things matter.',
    recognizedText: 'I sink tree things matter.',
    missedWords: [
      { word: 'think', soundCategories: ['th'] },
      { word: 'three', soundCategories: ['th'] },
    ],
  },
  emailSessions: {
    id: FIXTURE_IDS.other,
    ...timestamps,
    schemaVersion: 1,
    scenario: 'thank-you',
    step: 'draft',
    plan: '- remercier\n- rappeler un point fort',
    subject: 'Thank you for your time',
    draft: 'Dear Ms Smith,',
    productionId: null,
  },
  drafts: { key: 'settings:profile-remarks', text: 'Brouillon en cours', updatedAt: T0 },
  syncOutbox: { seq: 1, table: 'cards', docId: FIXTURE_IDS.card, queuedAt: T0 },
  syncMeta: { key: 'cursor', value: 0 },
  usageSnapshot: {
    id: 'usage',
    fetchedAt: T0,
    monthlyBudgetUsd: 10,
    monthStart: '2026-09-01',
    resetsOn: '2026-10-01',
    monthUsd: 1.2,
    todayUsd: 0.02,
    timeZone: 'Europe/Paris',
    byTask: [{ task: 'correct-production', calls: 40, costUsd: 1.1 }],
  },
  quarantine: {
    id: FIXTURE_IDS.other,
    table: 'drafts',
    key: 'settings:profile-remarks',
    record: { key: 'settings:profile-remarks', text: 42, updatedAt: T0 },
    reason: 'text: expected string',
    quarantinedAt: T0,
  },
};
