import { exercisesOf } from '../../builders.ts';
import type { NotionContentInput } from '../../schema.ts';
import { REVIEW } from './review.ts';

const { choice, fill, transform, place, translate } = exercisesOf(
  'tense-present-simple-vs-continuous',
  REVIEW,
);

const HABIT = 'Habitude ou routine';
const PERMANENT = 'Situation stable ou permanente';
const GENERAL = 'Vérité générale';
const NOW = 'Action en cours au moment où l’on parle';
const TEMPORARY = 'Situation temporaire';
const STATE = 'Verbe d’état : opinion, connaissance, possession…';

export const EXERCISES: NotionContentInput['exercises'] = [
  // Step 2: recognize
  choice(1, {
    sentence: 'I usually ___ the train, but today I’m taking the bus.',
    options: ['take', 'am taking'],
    answer: 'take',
    reasons: [HABIT, NOW, TEMPORARY],
    reason: HABIT,
    explanation: '_Usually_ : une habitude, donc le présent simple. _Today_ marque l’exception.',
  }),
  choice(2, {
    sentence: 'Look! The CEO ___ into the building.',
    options: ['is walking', 'walks'],
    answer: 'is walking',
    reasons: [NOW, HABIT, STATE],
    reason: NOW,
    explanation: '_Look!_ : on montre ce qui se passe à l’instant.',
  }),
  choice(3, {
    sentence: 'Sorry, I ___ his name.',
    options: ['don’t know', 'am not knowing'],
    answer: 'don’t know',
    reasons: [STATE, NOW, HABIT],
    reason: STATE,
    explanation: '_Know_ est un verbe d’état : présent simple, même pour maintenant.',
  }),
  choice(4, {
    sentence: 'She ___ in Paris, but this month she’s working in London.',
    options: ['works', 'is working'],
    answer: 'works',
    reasons: [PERMANENT, TEMPORARY, NOW],
    reason: PERMANENT,
    explanation: 'Paris est son lieu de travail habituel ; Londres, une situation temporaire.',
  }),
  choice(5, {
    sentence: 'At the moment we ___ a new CRM, so expect a few problems.',
    options: ['are testing', 'test'],
    answer: 'are testing',
    reasons: [TEMPORARY, HABIT, STATE],
    reason: TEMPORARY,
    explanation: 'Le test dure un temps limité : présent continu.',
  }),
  choice(6, {
    sentence: 'This building ___ to a pension fund.',
    options: ['belongs', 'is belonging'],
    answer: 'belongs',
    reasons: [STATE, TEMPORARY, NOW],
    reason: STATE,
    explanation: '_Belong_ exprime la possession : c’est un verbe d’état.',
  }),
  choice(7, {
    sentence: 'What ___? — I’m a teacher.',
    options: ['do you do', 'are you doing'],
    answer: 'do you do',
    reasons: [
      'Question sur le métier, une situation stable',
      'Question sur une action en cours',
      'Question sur une situation temporaire',
    ],
    reason: 'Question sur le métier, une situation stable',
    explanation:
      '_What do you do?_ demande la profession ; _What are you doing?_, l’action en cours.',
  }),
  choice(8, {
    sentence: 'Can you turn the music down? I ___ to concentrate.',
    options: ['am trying', 'try'],
    answer: 'am trying',
    reasons: [NOW, HABIT, STATE],
    reason: NOW,
    explanation: 'On demande de baisser la musique maintenant : l’effort est en cours.',
  }),
  choice(9, {
    sentence: 'I ___ tea to coffee.',
    options: ['prefer', 'am preferring'],
    answer: 'prefer',
    reasons: [STATE, NOW, TEMPORARY],
    reason: STATE,
    explanation: '_Prefer_ exprime un goût : c’est un verbe d’état, au présent simple.',
  }),
  choice(10, {
    sentence: 'Please be quiet: I ___ about your proposal.',
    options: ['am thinking', 'think'],
    answer: 'am thinking',
    reasons: [NOW, STATE, HABIT],
    reason: NOW,
    explanation: '_Think about_ : réfléchir, une activité en cours. Le continu est possible.',
  }),
  choice(11, {
    sentence: 'Our company ___ two offices, in Lyon and in Madrid.',
    options: ['has', 'is having'],
    answer: 'has',
    reasons: [STATE, NOW, TEMPORARY],
    reason: STATE,
    explanation: '_Have_ au sens de posséder : verbe d’état, présent simple.',
  }),
  choice(12, {
    sentence: 'Sorry, she can’t answer: she ___ lunch with a client.',
    options: ['is having', 'has'],
    answer: 'is having',
    reasons: [NOW, STATE, HABIT],
    reason: NOW,
    explanation: '_Have lunch_ est une action : elle a lieu maintenant, donc _is having_.',
  }),
  choice(13, {
    sentence: 'Money ___ value when prices go up.',
    options: ['loses', 'is losing'],
    answer: 'loses',
    reasons: [GENERAL, NOW, TEMPORARY],
    reason: GENERAL,
    explanation: 'Un mécanisme toujours vrai : vérité générale, présent simple.',
  }),

  // Step 3: practise
  fill(1, {
    sentence: 'Right now, the team ___ the quarterly figures.',
    verb: 'check',
    meaningFr: 'En ce moment même, l’équipe vérifie les chiffres trimestriels.',
    accepted: ['is checking', 'are checking'],
    knownErrors: ['checks', 'check'],
    explanation:
      '_Right now_ : action en cours. En anglais britannique, _team_ peut aussi prendre un verbe au pluriel.',
  }),
  fill(2, {
    sentence: 'She ___ three languages fluently.',
    verb: 'speak',
    meaningFr: 'Elle parle couramment trois langues.',
    accepted: ['speaks'],
    knownErrors: ['speak'],
    explanation: 'Une compétence stable : présent simple, _speaks_.',
  }),
  fill(3, {
    sentence: 'I ___ what this chart shows.',
    verb: 'understand (à la forme négative)',
    meaningFr: 'Je ne comprends pas ce que montre ce graphique.',
    accepted: ['don’t understand'],
    knownErrors: ['doesn’t understand', 'not understand'],
    explanation: '_Understand_ est un verbe d’état : _I don’t understand_.',
  }),
  fill(4, {
    sentence: 'Can you call back? He ___ a client at the moment.',
    verb: 'meet',
    meaningFr: 'Pouvez-vous rappeler ? Il rencontre un client en ce moment.',
    accepted: ['is meeting'],
    knownErrors: ['meets', 'meet'],
    explanation: 'Le rendez-vous a lieu maintenant : _is meeting_.',
  }),
  fill(5, {
    sentence: 'Our firm ___ over 200 people.',
    verb: 'employ',
    meaningFr: 'Notre cabinet emploie plus de 200 personnes.',
    accepted: ['employs'],
    knownErrors: ['employ', 'employing'],
    explanation: 'Un fait stable : présent simple, avec le _-s_ de la 3e personne.',
  }),
  fill(6, {
    sentence: 'This month, I ___ on a big audit.',
    verb: 'work',
    meaningFr: 'Ce mois-ci, je travaille sur un gros audit.',
    accepted: ['am working'],
    knownErrors: ['am work', 'working'],
    explanation: '_This month_ : situation temporaire, présent continu.',
  }),
  fill(7, {
    sentence: 'Prices usually ___ in December.',
    verb: 'rise',
    meaningFr: 'Les prix augmentent généralement en décembre.',
    accepted: ['rise'],
    knownErrors: ['rises', 'raise'],
    explanation:
      '_Usually_ : habitude, présent simple. _Prices_ est au pluriel. _Rise_ (sans complément), et non _raise_.',
  }),
  fill(8, {
    sentence: 'What ___ about? You look worried.',
    verb: 'you / think',
    meaningFr: 'À quoi penses-tu ? Tu as l’air inquiet.',
    accepted: ['are you thinking'],
    knownErrors: ['do you thinking', 'you are thinking'],
    explanation: 'Une réflexion en cours : _are you thinking about_.',
  }),
  fill(9, {
    sentence: 'Sorry, I ___ your name.',
    verb: 'remember (à la forme négative)',
    meaningFr: 'Désolé, je ne me souviens pas de ton nom.',
    accepted: ['don’t remember'],
    knownErrors: ['not remember', 'doesn’t remember'],
    explanation: '_Remember_ est un verbe d’état : _I don’t remember_.',
  }),
  fill(10, {
    sentence: 'The central bank ___ its interest rates every six weeks.',
    verb: 'review',
    meaningFr: 'La banque centrale réexamine ses taux d’intérêt toutes les six semaines.',
    accepted: ['reviews'],
    knownErrors: ['review'],
    explanation: 'Un rythme régulier : présent simple, _reviews_.',
  }),
  transform(11, {
    source: 'I work from home.',
    instructionFr: 'Dis que c’est temporaire : ajoute « this week » à la fin et change le temps.',
    accepted: ['I’m working from home this week.', 'This week I’m working from home.'],
    knownErrors: ['I am work from home this week.'],
    explanation: 'Situation temporaire : présent continu, _I’m working_.',
  }),
  transform(12, {
    source: 'He is having a car.',
    instructionFr: 'Corrige la phrase : ici, « have » exprime la possession.',
    accepted: ['He has a car.', 'He has got a car.'],
    knownErrors: ['He is have a car.'],
    explanation:
      '_Have_ au sens de posséder est un verbe d’état : _He has a car_ (ou _He’s got a car_).',
  }),
  transform(13, {
    source: 'I’m knowing the answer.',
    instructionFr: 'Corrige la phrase : « know » est un verbe d’état.',
    accepted: ['I know the answer.'],
    knownErrors: ['I knowing the answer.'],
    explanation: 'Un verbe d’état reste au présent simple : _I know_.',
  }),
  place(14, {
    sentence: 'I take the train, but this week I’m driving.',
    word: 'usually',
    meaningFr: 'D’habitude, je prends le train, mais cette semaine je prends la voiture.',
    accepted: [
      'I usually take the train, but this week I’m driving.',
      'Usually I take the train, but this week I’m driving.',
    ],
    knownErrors: ['I take usually the train, but this week I’m driving.'],
    explanation: 'L’adverbe de fréquence se place avant le verbe : _I usually take_.',
  }),

  // Step 4: translate
  translate(1, {
    sentenceFr: 'D’habitude, je prends le bus.',
    hint: 'Une habitude.',
    difficulty: 1,
    accepted: [
      'I usually take the bus.',
      'Usually I take the bus.',
      'I normally take the bus.',
      'I generally take the bus.',
      'I usually go by bus.',
    ],
    knownErrors: ['I usually am taking the bus.', 'I take usually the bus.'],
    explanation: 'Une habitude : présent simple, l’adverbe avant le verbe.',
  }),
  translate(2, {
    sentenceFr: 'Elle présente les résultats en ce moment.',
    hint: 'Une action en cours.',
    difficulty: 1,
    accepted: [
      'She’s presenting the results at the moment.',
      'She’s presenting the results right now.',
      'She’s presenting the results now.',
      'She’s currently presenting the results.',
      'At the moment she’s presenting the results.',
    ],
    knownErrors: ['She presenting the results at the moment.'],
    explanation: 'L’action a lieu en ce moment : _she’s presenting_.',
  }),
  translate(3, {
    sentenceFr: 'Je ne connais pas ce client.',
    hint: 'Un verbe d’état, à la forme négative.',
    difficulty: 1,
    accepted: [
      'I don’t know this client.',
      'I don’t know that client.',
      'I don’t know this customer.',
      'I don’t know that customer.',
    ],
    knownErrors: ['I’m not knowing this client.', 'I don’t knowing this client.'],
    explanation: '_Know_ est un verbe d’état : _I don’t know_, jamais au continu.',
  }),
  translate(4, {
    sentenceFr: 'Qu’est-ce que tu fais dans la vie ?',
    hint: 'Une question sur le métier, une situation stable.',
    difficulty: 1,
    accepted: ['What do you do?', 'What do you do for a living?', 'What’s your job?'],
    knownErrors: ['What are you doing in the life?'],
    explanation: '_What do you do?_ demande la profession : présent simple.',
  }),
  translate(5, {
    sentenceFr: 'Il travaille à Genève, mais ce mois-ci il travaille à Londres.',
    hint: 'Une situation stable, puis une situation temporaire.',
    difficulty: 2,
    accepted: [
      'He works in Geneva, but this month he’s working in London.',
      'He works in Geneva, but he’s working in London this month.',
      'He works in Geneva but this month he’s working in London.',
    ],
    explanation: 'Stable : _he works_. Temporaire : _he’s working_.',
  }),
  translate(6, {
    sentenceFr: 'Je pense que tu as raison.',
    hint: 'Une opinion : verbe d’état.',
    difficulty: 2,
    accepted: ['I think you’re right.', 'I think that you’re right.'],
    knownErrors: ['I think you have right.', 'I think that you have right.'],
    explanation: 'Opinion : _I think_ (verbe d’état). « Avoir raison » se dit _be right_.',
  }),
  translate(7, {
    sentenceFr: 'Ce document appartient au service juridique.',
    hint: 'Un verbe d’état, sujet singulier.',
    difficulty: 2,
    accepted: [
      'This document belongs to the legal department.',
      'This document belongs to the legal team.',
      'That document belongs to the legal department.',
      'That document belongs to the legal team.',
    ],
    knownErrors: ['This document is belonging to the legal department.'],
    explanation: '_Belong_ est un verbe d’état : _belongs to_.',
  }),
  translate(8, {
    sentenceFr: 'À quoi est-ce que tu penses ?',
    hint: 'Une réflexion en cours, maintenant.',
    difficulty: 2,
    accepted: ['What are you thinking about?', 'What are you thinking of?'],
    knownErrors: ['What do you thinking about?', 'What you are thinking about?'],
    explanation: 'Réfléchir en ce moment : _What are you thinking about?_',
  }),
  translate(9, {
    sentenceFr: 'D’habitude, je travaille au bureau, mais cette semaine je travaille chez moi.',
    hint: 'Une habitude, puis une exception temporaire.',
    difficulty: 3,
    accepted: [
      'I usually work at the office, but this week I’m working from home.',
      'I usually work in the office, but this week I’m working from home.',
      'I usually work from the office, but this week I’m working from home.',
      'I usually work at the office, but this week I’m working at home.',
      'I usually work in the office, but this week I’m working at home.',
      'Usually I work at the office, but this week I’m working from home.',
      'Usually I work in the office, but this week I’m working from home.',
      'I usually work at the office, but I’m working from home this week.',
      'I usually work in the office, but I’m working from home this week.',
    ],
    knownErrors: ['I usually am working at the office, but this week I’m working from home.'],
    explanation: 'Habitude : _I usually work_. Exception temporaire : _I’m working_.',
  }),
  translate(10, {
    sentenceFr: 'Notre équipe a deux data scientists et elle en recrute un troisième.',
    hint: 'Une possession, puis une action temporaire.',
    difficulty: 3,
    accepted: [
      'Our team has two data scientists and it’s hiring a third one.',
      'Our team has two data scientists and it’s hiring a third.',
      'Our team has two data scientists and is hiring a third one.',
      'Our team has two data scientists and is hiring a third.',
      'Our team has two data scientists and it’s recruiting a third one.',
      'Our team has two data scientists and is recruiting a third one.',
      'Our team has two data scientists and we’re hiring a third one.',
    ],
    knownErrors: ['Our team is having two data scientists and it’s hiring a third one.'],
    explanation: 'Possession : _has_ (verbe d’état). Recrutement en cours : _is hiring_.',
  }),
  translate(11, {
    sentenceFr: 'Je ne comprends pas pourquoi les ventes baissent ce trimestre.',
    hint: 'Un verbe d’état, puis une évolution temporaire.',
    difficulty: 3,
    accepted: [
      'I don’t understand why sales are falling this quarter.',
      'I don’t understand why sales are dropping this quarter.',
      'I don’t understand why sales are going down this quarter.',
      'I don’t understand why sales are decreasing this quarter.',
      'I don’t understand why sales are declining this quarter.',
      'I don’t understand why the sales are falling this quarter.',
    ],
    knownErrors: ['I don’t understand why sales are raising this quarter.'],
    explanation:
      '_Understand_ reste au présent simple ; la baisse, temporaire, est au présent continu.',
  }),
];
