/**
 * `generatedExercises` table (class D, P3): exercises generated by the model,
 * validated and kept so that they are never generated twice (COST-09).
 */
import { z } from 'zod';
import { notionIdSchema } from '../../domain/curriculum/notion-id.ts';
import { stepSchema } from '../../domain/curriculum/progress.ts';
import { uuidSchema } from '../../domain/primitives.ts';
import { documentTimestamps } from './common.ts';

export const generatedExerciseDocumentSchema = z.strictObject({
  id: uuidSchema,
  ...documentTimestamps,
  schemaVersion: z.literal(1),
  notionId: notionIdSchema,
  step: stepSchema,
  /**
   * The exercise itself, in the same format as the core exercises. That format
   * is defined in phase 3; until then only JSON-serializable data is accepted.
   */
  exercise: z.json(),
  model: z.string().min(1).max(100),
  promptVersion: z.string().min(1).max(100),
  status: z.enum(['active', 'reported']),
});
export type GeneratedExerciseDocument = z.infer<typeof generatedExerciseDocumentSchema>;
