import { exercisesOf } from '../../builders.ts';
import type { NotionContentInput } from '../../schema.ts';
import { REVIEW } from './review.ts';

const { choice, fill, transform, translate } = exercisesOf('tense-future', REVIEW);

const DECISION = 'Décision prise au moment où l’on parle';
const PLAN = 'Intention déjà décidée';
const ARRANGEMENT = 'Rendez-vous ou arrangement déjà fixé';
const EVIDENCE = 'Prédiction fondée sur un indice présent';
const PREDICTION = 'Prévision ou opinion sur l’avenir';
const PROMISE = 'Promesse';
const TIME_CLAUSE = 'Après _when_, _if_ ou _as soon as_ : présent pour un futur';
const TIMETABLE = 'Horaire ou programme officiel';

export const EXERCISES: NotionContentInput['exercises'] = [
  // Step 2: recognize
  choice(1, {
    sentence: 'I’ll call you when I ___ at the airport.',
    options: ['arrive', 'will arrive', 'am going to arrive'],
    answer: 'arrive',
    reasons: [TIME_CLAUSE, PREDICTION, PLAN],
    reason: TIME_CLAUSE,
    explanation: 'Après _when_, le futur s’exprime par le présent : _when I arrive_.',
  }),
  choice(2, {
    sentence: 'The phone’s ringing. — Don’t move, I ___ answer it.',
    options: ['will', 'am', 'going to'],
    answer: 'will',
    reasons: [DECISION, PLAN, ARRANGEMENT],
    reason: DECISION,
    explanation: 'Décision prise à l’instant : _will_ (_I’ll answer it_).',
  }),
  choice(3, {
    sentence: 'I’ve decided: I ___ apply for the master’s programme in London.',
    options: ['am going to', 'going to', 'am go to'],
    answer: 'am going to',
    reasons: [PLAN, DECISION, EVIDENCE],
    reason: PLAN,
    explanation: '_I’ve decided_ : intention déjà décidée, _be going to_ (avec _am_).',
  }),
  choice(4, {
    sentence: 'Look at those clouds! It ___ rain.',
    options: ['is going to', 'going to', 'is go to'],
    answer: 'is going to',
    reasons: [EVIDENCE, DECISION, ARRANGEMENT],
    reason: EVIDENCE,
    explanation: 'Les nuages sont un indice présent : _it’s going to rain_.',
  }),
  choice(5, {
    sentence: 'I ___ the client at 10 tomorrow; it’s in my diary.',
    options: ['am meeting', 'meeting', 'am meet'],
    answer: 'am meeting',
    reasons: [ARRANGEMENT, DECISION, EVIDENCE],
    reason: ARRANGEMENT,
    explanation: 'Rendez-vous fixé (noté dans l’agenda) : présent continu.',
  }),
  choice(6, {
    sentence: 'I think interest rates ___ next year.',
    options: ['will fall', 'will falling', 'will to fall'],
    answer: 'will fall',
    reasons: [PREDICTION, ARRANGEMENT, TIME_CLAUSE],
    reason: PREDICTION,
    explanation: '_I think_ + _will_ : une opinion sur l’avenir. Après _will_, base verbale.',
  }),
  choice(7, {
    sentence: 'Don’t worry, I ___ tell anyone. I promise.',
    options: ['won’t', 'won’t to', 'am not'],
    answer: 'won’t',
    reasons: [PROMISE, PLAN, ARRANGEMENT],
    reason: PROMISE,
    explanation:
      'Une promesse : _will_, ici à la forme négative _won’t_, suivi de la base verbale.',
  }),
  choice(8, {
    sentence: 'As soon as the results ___ in, I’ll send them to you.',
    options: ['come', 'will come', 'are going to come'],
    answer: 'come',
    reasons: [TIME_CLAUSE, PREDICTION, ARRANGEMENT],
    reason: TIME_CLAUSE,
    explanation: 'Après _as soon as_, présent pour un futur : _as soon as the results come in_.',
  }),
  choice(9, {
    sentence: 'We ___ a new analyst next month: the contract is already signed.',
    options: ['are hiring', 'hiring', 'are hire'],
    answer: 'are hiring',
    reasons: [ARRANGEMENT, DECISION, PREDICTION],
    reason: ARRANGEMENT,
    explanation: 'Le contrat est signé : arrangement fixé, présent continu.',
  }),
  choice(10, {
    sentence: 'If the market ___, we’ll lose money.',
    options: ['falls', 'will fall', 'fall'],
    answer: 'falls',
    reasons: [TIME_CLAUSE, PREDICTION, PLAN],
    reason: TIME_CLAUSE,
    explanation: 'Après _if_, présent pour un futur ; sujet singulier : _falls_.',
  }),
  choice(11, {
    sentence: 'I’m tired. I think I ___ go home early.',
    options: ['will', 'am', 'going'],
    answer: 'will',
    reasons: [DECISION, ARRANGEMENT, TIMETABLE],
    reason: DECISION,
    explanation: 'La décision se prend maintenant : _I think I’ll go home early_.',
  }),
  choice(12, {
    sentence: 'According to the programme, the conference ___ on 12 May.',
    options: ['starts', 'start', 'starting'],
    answer: 'starts',
    reasons: [TIMETABLE, DECISION, PLAN],
    reason: TIMETABLE,
    explanation: 'Un programme officiel : présent simple, _starts_.',
  }),

  // Step 3: practise
  fill(1, {
    sentence: 'I’ll phone you when I ___ the figures.',
    verb: 'get',
    meaningFr: 'Je t’appellerai quand j’aurai les chiffres.',
    accepted: ['get', 'have', 'have got'],
    knownErrors: ['will get', 'am going to get'],
    explanation: 'Après _when_, présent pour un futur : _when I get the figures_.',
  }),
  fill(2, {
    sentence: 'She ___ her new job on Monday. Everything is arranged.',
    verb: 'start',
    meaningFr: 'Elle commence son nouveau travail lundi. Tout est organisé.',
    accepted: ['is starting', 'starts', 'will start', 'is going to start'],
    knownErrors: ['starting', 'start'],
    explanation:
      'Arrangement fixé : le présent continu (_is starting_) est le plus naturel ; les autres formes du futur sont aussi justes.',
  }),
  fill(3, {
    sentence: 'Look at the traffic! We ___ late.',
    verb: 'be',
    meaningFr: 'Regarde la circulation ! Nous allons être en retard.',
    accepted: ['are going to be', 'will be'],
    knownErrors: ['are being', 'be going to'],
    explanation: 'Un indice présent (la circulation) : _we’re going to be late_.',
  }),
  fill(4, {
    sentence: 'I ___ you the file tonight, I promise.',
    verb: 'send',
    meaningFr: 'Je t’enverrai le fichier ce soir, promis.',
    accepted: ['will send', 'am going to send'],
    knownErrors: ['will sending', 'will to send'],
    explanation: 'Une promesse : _I’ll send_.',
  }),
  fill(5, {
    sentence: 'If it ___ tomorrow, we’ll cancel the trip.',
    verb: 'rain',
    meaningFr: 'S’il pleut demain, nous annulerons le voyage.',
    accepted: ['rains'],
    knownErrors: ['will rain', 'rain'],
    explanation: 'Après _if_, présent pour un futur : _if it rains_.',
  }),
  fill(6, {
    sentence: 'We ___ the budget next week: the meeting is on Tuesday.',
    verb: 'discuss',
    meaningFr: 'Nous discuterons du budget la semaine prochaine : la réunion est mardi.',
    accepted: ['are discussing', 'are going to discuss', 'will discuss'],
    knownErrors: ['discussing', 'are discuss'],
    explanation: 'Réunion déjà fixée : _we’re discussing_ est le plus naturel.',
  }),
  fill(7, {
    sentence: 'What ___ after your internship?',
    verb: 'you / do',
    meaningFr: 'Que vas-tu faire après ton stage ?',
    accepted: ['are you going to do', 'will you do', 'are you doing'],
    knownErrors: ['you are going to do', 'do you going to do'],
    explanation: 'Question sur une intention : _What are you going to do…?_',
  }),
  fill(8, {
    sentence: 'I’m sure the client ___ the offer.',
    verb: 'accept',
    meaningFr: 'Je suis sûr que le client acceptera l’offre.',
    accepted: ['will accept', 'is going to accept'],
    knownErrors: ['will accepts', 'will accepting'],
    explanation: 'Une prévision : _will accept_ (base verbale après _will_).',
  }),
  fill(9, {
    sentence: 'Before you ___, please switch off the lights.',
    verb: 'leave',
    meaningFr: 'Avant de partir, éteins les lumières, s’il te plaît.',
    accepted: ['leave', 'go'],
    knownErrors: ['will leave', 'are going to leave'],
    explanation: 'Après _before_, présent pour un futur : _before you leave_.',
  }),
  fill(10, {
    sentence: 'The train to Bern ___ at 7:32.',
    verb: 'leave',
    meaningFr: 'Le train pour Berne part à 7 h 32.',
    accepted: ['leaves', 'is leaving', 'will leave'],
    knownErrors: ['leave', 'leaving'],
    explanation: 'Un horaire : présent simple, _leaves_.',
  }),
  transform(11, {
    source: 'I will call you.',
    instructionFr: 'Mets la phrase à la forme négative.',
    accepted: ['I won’t call you.'],
    knownErrors: ['I don’t will call you.', 'I won’t to call you.'],
    explanation: 'Négation : _will not_ (_won’t_) + base verbale.',
  }),
  transform(12, {
    source: 'She is going to apply for the job.',
    instructionFr: 'Mets la phrase à la forme interrogative.',
    accepted: ['Is she going to apply for the job?'],
    knownErrors: ['Does she going to apply for the job?', 'Is she going apply for the job?'],
    explanation: 'Question : _Is_ + sujet + _going to_ + base verbale.',
  }),
  transform(13, {
    source: 'I will tell you when I will know.',
    instructionFr: 'Corrige la phrase : après « when », pas de futur.',
    accepted: ['I will tell you when I know.'],
    knownErrors: ['I will tell you when I will know.'],
    explanation: 'Après _when_, présent pour un futur : _when I know_.',
  }),

  // Step 4: translate
  translate(1, {
    sentenceFr: 'Je t’appellerai quand j’arriverai.',
    hint: 'Attention au verbe qui suit « quand ».',
    difficulty: 1,
    accepted: [
      'I’ll call you when I arrive.',
      'I’ll phone you when I arrive.',
      'I’ll ring you when I arrive.',
      'I’ll call you when I get there.',
      'I’ll call you when I get here.',
      'When I arrive, I’ll call you.',
    ],
    knownErrors: ['I’ll call you when I will arrive.'],
    explanation: '_Will_ dans la principale, présent après _when_ : _when I arrive_.',
  }),
  translate(2, {
    sentenceFr: 'Il va pleuvoir, regarde le ciel !',
    hint: 'Une prédiction fondée sur ce que l’on voit.',
    difficulty: 1,
    accepted: [
      'It’s going to rain, look at the sky!',
      'Look at the sky, it’s going to rain!',
      'It will rain, look at the sky!',
    ],
    knownErrors: ['It goes to rain, look at the sky!'],
    explanation:
      'Indice présent : _It’s going to rain._ « Il va » ne se traduit pas par _it goes_.',
  }),
  translate(3, {
    sentenceFr: 'Je rencontre le client demain à 10 heures.',
    hint: 'Un rendez-vous déjà fixé.',
    difficulty: 1,
    accepted: [
      'I’m meeting the client tomorrow at 10.',
      'I’m meeting the client tomorrow at 10 o’clock.',
      'I’m meeting the client tomorrow at ten.',
      'I’m meeting the client at 10 tomorrow.',
      'I’m meeting the client tomorrow at 10 a.m.',
      'I’m going to meet the client tomorrow at 10.',
      'I’ll meet the client tomorrow at 10.',
      'I’m seeing the client tomorrow at 10.',
    ],
    knownErrors: ['I meeting the client tomorrow at 10.'],
    explanation: 'Rendez-vous fixé : présent continu, _I’m meeting_.',
  }),
  translate(4, {
    sentenceFr: 'Ne t’inquiète pas, je t’aiderai.',
    hint: 'Une promesse, faite sur le moment.',
    difficulty: 1,
    accepted: ['Don’t worry, I’ll help you.', 'Don’t worry, I will help you.'],
    knownErrors: ['Don’t worry, I help you.', 'Don’t worry, I’ll to help you.'],
    explanation: 'Promesse : _I’ll help you_.',
  }),
  translate(5, {
    sentenceFr: 'Qu’est-ce que tu vas faire après ton stage ?',
    hint: 'Une question sur une intention.',
    difficulty: 2,
    accepted: [
      'What are you going to do after your internship?',
      'What will you do after your internship?',
      'What are you doing after your internship?',
      'What are you going to do after your work placement?',
    ],
    knownErrors: [
      'What you are going to do after your internship?',
      'What do you go to do after your internship?',
    ],
    explanation: 'Intention : _What are you going to do…?_ (_are_ avant le sujet).',
  }),
  translate(6, {
    sentenceFr: 'Si les taux baissent, nous achèterons plus d’actions.',
    hint: 'Après « si », quel temps pour parler du futur ?',
    difficulty: 2,
    accepted: [
      'If rates fall, we’ll buy more shares.',
      'If interest rates fall, we’ll buy more shares.',
      'If rates go down, we’ll buy more shares.',
      'If rates drop, we’ll buy more shares.',
      'If rates fall, we’ll buy more stocks.',
      'If interest rates go down, we’ll buy more shares.',
      'We’ll buy more shares if rates fall.',
    ],
    knownErrors: ['If rates will fall, we’ll buy more shares.'],
    explanation: 'Après _if_, présent : _if rates fall_ ; puis _will_ dans la principale.',
  }),
  translate(7, {
    sentenceFr: 'J’ai décidé : je vais changer de poste l’année prochaine.',
    hint: 'Une intention déjà décidée.',
    difficulty: 2,
    accepted: [
      'I’ve decided: I’m going to change jobs next year.',
      'I’ve decided that I’m going to change jobs next year.',
      'I’ve decided: I’m going to change my job next year.',
      'I’ve decided: I’m going to change positions next year.',
      'I’ve decided: I’m changing jobs next year.',
      'I’ve decided: I’ll change jobs next year.',
      'I’ve decided to change jobs next year.',
    ],
    knownErrors: ['I’ve decided: I go to change jobs next year.'],
    explanation: 'Intention déjà décidée : _I’m going to change jobs_.',
  }),
  translate(8, {
    sentenceFr: 'Dès que j’aurai les résultats, je te les enverrai.',
    hint: 'Après « dès que », quel temps pour parler du futur ?',
    difficulty: 2,
    accepted: [
      'As soon as I get the results, I’ll send them to you.',
      'As soon as I have the results, I’ll send them to you.',
      'As soon as I receive the results, I’ll send them to you.',
      'As soon as I’ve got the results, I’ll send them to you.',
      'As soon as I get the results, I’ll send them over.',
      'I’ll send you the results as soon as I get them.',
      'I’ll send you the results as soon as I have them.',
      'I’ll send them to you as soon as I get the results.',
    ],
    knownErrors: [
      'As soon as I will get the results, I’ll send them to you.',
      'As soon as I will have the results, I’ll send them to you.',
    ],
    explanation: 'Après _as soon as_, présent : _as soon as I get the results_.',
  }),
  translate(9, {
    sentenceFr: 'Nous lançons le produit en mars ; je pense que les ventes seront bonnes.',
    hint: 'Un projet fixé, puis une opinion sur l’avenir.',
    difficulty: 3,
    accepted: [
      'We’re launching the product in March; I think sales will be good.',
      'We’re launching the product in March; I think the sales will be good.',
      'We’re launching the product in March, and I think sales will be good.',
      'We’re going to launch the product in March; I think sales will be good.',
      'We launch the product in March; I think sales will be good.',
      'We’re launching the product in March; I think sales are going to be good.',
      'We’ll launch the product in March; I think sales will be good.',
    ],
    knownErrors: ['We’re launching the product in March; I think sales will being good.'],
    explanation: 'Projet fixé : _we’re launching_. Opinion sur l’avenir : _I think… will_.',
  }),
  translate(10, {
    sentenceFr: 'Je ne pourrai pas venir à la réunion, mais je vous enverrai mes notes avant.',
    hint: '« Pouvoir » au futur, puis une promesse.',
    difficulty: 3,
    accepted: [
      'I won’t be able to come to the meeting, but I’ll send you my notes beforehand.',
      'I won’t be able to come to the meeting, but I’ll send you my notes before.',
      'I won’t be able to come to the meeting, but I’ll send you my notes before it.',
      'I won’t be able to attend the meeting, but I’ll send you my notes beforehand.',
      'I won’t be able to make it to the meeting, but I’ll send you my notes beforehand.',
      'I won’t be able to come to the meeting, but I’ll send you my notes in advance.',
      'I can’t come to the meeting, but I’ll send you my notes beforehand.',
    ],
    knownErrors: ['I won’t can come to the meeting, but I’ll send you my notes beforehand.'],
    explanation: '« Je ne pourrai pas » : _I won’t be able to_ ; promesse : _I’ll send_.',
  }),
  translate(11, {
    sentenceFr: 'Quand tu verras le directeur, dis-lui que je rappellerai demain.',
    hint: 'Après « quand », quel temps ? Puis une promesse.',
    difficulty: 3,
    accepted: [
      'When you see the director, tell him I’ll call back tomorrow.',
      'When you see the director, tell her I’ll call back tomorrow.',
      'When you see the director, tell him that I’ll call back tomorrow.',
      'When you see the director, tell her that I’ll call back tomorrow.',
      'When you see the director, tell him I’ll call him back tomorrow.',
      'When you see the director, tell her I’ll call her back tomorrow.',
      'When you see the manager, tell him I’ll call back tomorrow.',
      'When you see the manager, tell her I’ll call back tomorrow.',
    ],
    knownErrors: ['When you will see the director, tell him I’ll call back tomorrow.'],
    explanation: 'Après _when_, présent : _when you see_ ; puis _I’ll call back_.',
  }),
];
