/**
 * The Edge Function imports the AI contract from a copy of shared/ai placed
 * in supabase/functions/_shared/ai, the layout Supabase documents for code
 * shared by functions (D-061, resolves D-030). The copy is generated by
 * `npm run sync:shared` and checked by a test, so that it never drifts.
 */
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';

export const SOURCE_DIR = 'shared/ai';
export const COPY_DIR = 'supabase/functions/_shared/ai';

/** Files of `dir`, relative to it, with forward slashes, sorted. */
export function listFiles(dir: string): string[] {
  const files: string[] = [];
  function walk(relative: string): void {
    for (const entry of readdirSync(path.join(dir, relative), { withFileTypes: true })) {
      const next = relative === '' ? entry.name : `${relative}/${entry.name}`;
      if (entry.isDirectory()) walk(next);
      else files.push(next);
    }
  }
  walk('');
  return files.sort();
}

/** Tests stay with the source: the copy holds only what the function imports. */
function isCopied(file: string): boolean {
  return file.endsWith('.ts') && !file.endsWith('.test.ts');
}

function header(file: string): string {
  return `// Generated from ${SOURCE_DIR}/${file} by \`npm run sync:shared\`: do not edit (D-061).\n`;
}

/** Expected content of the copy: relative path → text. */
export function expectedCopy(root: string): Map<string, string> {
  const sourceDir = path.join(root, SOURCE_DIR);
  return new Map(
    listFiles(sourceDir)
      .filter(isCopied)
      .map((file) => [file, header(file) + readFileSync(path.join(sourceDir, file), 'utf8')]),
  );
}

/** Current content of the copy on disk. */
export function actualCopy(root: string): Map<string, string> {
  const copyDir = path.join(root, COPY_DIR);
  let files: string[];
  try {
    files = listFiles(copyDir);
  } catch {
    return new Map();
  }
  return new Map(files.map((file) => [file, readFileSync(path.join(copyDir, file), 'utf8')]));
}

/** Rewrites the copy from the source. */
export function writeCopy(root: string): void {
  const copyDir = path.join(root, COPY_DIR);
  rmSync(copyDir, { recursive: true, force: true });
  for (const [file, content] of expectedCopy(root)) {
    const target = path.join(copyDir, file);
    mkdirSync(path.dirname(target), { recursive: true });
    writeFileSync(target, content);
  }
}
