/**
 * Messages between the client and the Edge Function "ai" (docs/ARCHITECTURE.md
 * §8). Both sides validate them with these schemas (ARC-05).
 *
 * - `POST`: `{ task, input, requestId }` runs a task. The client never sends
 *   a prompt (D-017).
 * - `GET ?timeZone=…`: the learner's spending and the monthly cap, read from
 *   the call log; no model is called.
 */
import { z } from 'zod';
import { MODELS } from './models.ts';
import { aiTaskNameSchema, TASK_CONTRACTS } from './tasks.ts';

/** Largest request body accepted by the Edge Function. */
export const MAX_REQUEST_BYTES = 64 * 1024;

const usdSchema = z.number().nonnegative();

export const connectionCheckRequestSchema = z.strictObject({
  task: z.literal('connection-check'),
  /** Generated by the client for each user action: a double tap costs nothing. */
  requestId: z.uuid(),
  input: TASK_CONTRACTS['connection-check'].input,
});

export const aiRequestSchema = z.discriminatedUnion('task', [connectionCheckRequestSchema]);
export type AiRequest = z.infer<typeof aiRequestSchema>;

export const AI_ERROR_CODES = [
  /** No valid session: the learner must sign in again. */
  'unauthenticated',
  /** The account is not allowed to use the AI (`AI_ALLOWED_EMAILS`). */
  'forbidden',
  /** Unknown task, invalid input or body too large. */
  'invalid_request',
  /** This `requestId` was already received in the last ten minutes. */
  'duplicate_request',
  /** Too many calls in the last minute (COST-07). */
  'rate_limited',
  /** The monthly cap would be exceeded (COST-06). */
  'budget_exceeded',
  /** The model declined to answer. */
  'model_refusal',
  /** The answer reached `max_tokens` and was cut off. */
  'output_truncated',
  /** The answer did not match the task's schema, even after one new attempt. */
  'invalid_output',
  /** Anthropic could not be reached or returned an error. */
  'upstream_error',
  /** Misconfiguration or database error on the server. */
  'server_error',
] as const;
export const aiErrorCodeSchema = z.enum(AI_ERROR_CODES);
export type AiErrorCode = z.infer<typeof aiErrorCodeSchema>;

export const budgetStateSchema = z.strictObject({
  usedUsd: usdSchema,
  limitUsd: usdSchema,
  /** First day of the next month (UTC), when the cap starts again. */
  resetsOn: z.iso.date(),
});
export type BudgetState = z.infer<typeof budgetStateSchema>;

export const aiFailureSchema = z.strictObject({
  ok: z.literal(false),
  error: z.strictObject({
    code: aiErrorCodeSchema,
    budget: budgetStateSchema.optional(),
    retryAfterSeconds: z.int().positive().optional(),
  }),
});
export type AiFailure = z.infer<typeof aiFailureSchema>;

export const aiSuccessSchema = z.strictObject({
  ok: z.literal(true),
  requestId: z.uuid(),
  task: aiTaskNameSchema,
  model: z.enum([MODELS.fast, MODELS.capable]),
  promptVersion: z.string().min(1).max(100),
  costUsd: usdSchema,
  /** Validated by the Edge Function, and again by the client with the task's output schema. */
  output: z.unknown(),
});
export type AiSuccess = z.infer<typeof aiSuccessSchema>;

export const aiResponseSchema = z.discriminatedUnion('ok', [aiSuccessSchema, aiFailureSchema]);
export type AiResponse = z.infer<typeof aiResponseSchema>;

/** Spending of the learner (COST-08), answered to `GET`. */
export const aiUsageSchema = z.strictObject({
  ok: z.literal(true),
  monthlyBudgetUsd: usdSchema,
  /** Month used by the cap: UTC, like the cap itself. */
  monthStart: z.iso.date(),
  resetsOn: z.iso.date(),
  /** Actual costs, plus the reservations of calls still running. */
  monthUsd: usdSchema,
  /** Today in `timeZone`, the learner's time zone. */
  todayUsd: usdSchema,
  timeZone: z.string().min(1).max(64),
  byTask: z.array(
    z.strictObject({
      task: z.string().min(1).max(64),
      calls: z.int().nonnegative(),
      costUsd: usdSchema,
    }),
  ),
});
export type AiUsage = z.infer<typeof aiUsageSchema>;

export const aiUsageResponseSchema = z.discriminatedUnion('ok', [aiUsageSchema, aiFailureSchema]);

/** IANA time zone name, such as `Europe/Paris`; anything else is read as UTC. */
export const timeZoneSchema = z
  .string()
  .max(64)
  .regex(/^[A-Za-z]+(?:[/_+-][A-Za-z0-9]+)*$/);
