/**
 * Exercises generated by the model on request (CUR-07, COST-09): stored once
 * validated, reused, never generated twice. A reported exercise is never
 * shown again, but kept.
 *
 * Every check is made when storing and again when reading: an exercise that
 * comes from an import or another device is never shown unless it passes them
 * too (NO-05). One that fails is kept, never shown.
 */
import { reasonSetsOf } from '../../../shared/ai/reasons.ts';
import { checkExercise, STEP_OF_KIND, type Exercise } from '../../domain/curriculum/exercise.ts';
import type { NotionId } from '../../domain/curriculum/notion-id.ts';
import type { Step } from '../../domain/curriculum/progress.ts';
import { nextUpdatedAt, type Clock } from '../../domain/primitives.ts';
import type { AppDatabase } from '../database.ts';
import { parseRecord, writeRecord } from '../records.ts';
import type { GeneratedExerciseDocument } from '../schemas/generated-exercises.ts';

export interface NewGeneratedExercises {
  readonly notionId: NotionId;
  readonly exercises: readonly Exercise[];
  readonly model: string;
  readonly promptVersion: string;
}

/** True when a generated exercise of this notion can be graded locally (NO-05, D-081). */
export function isFitGeneratedExercise(notionId: NotionId, exercise: Exercise): boolean {
  return checkExercise(exercise, { reasonSets: reasonSetsOf(notionId) }).length === 0;
}

export interface GeneratedExerciseRepository {
  /** Active exercises of a notion and step, oldest first. */
  active(notionId: NotionId, step: Step): Promise<GeneratedExerciseDocument[]>;
  /** Stores the exercises fit for local grading; returns those stored. */
  add(batch: NewGeneratedExercises): Promise<GeneratedExerciseDocument[]>;
  /** The learner reports an exercise: it is never shown again. */
  report(id: string): Promise<void>;
}

export function createGeneratedExerciseRepository(
  db: AppDatabase,
  clock: Clock,
): GeneratedExerciseRepository {
  const table = db.table('generatedExercises');

  return {
    async active(notionId, step) {
      const raws: unknown[] = await table
        .where('[notionId+step]')
        .equals([notionId, step])
        .toArray();
      const documents: GeneratedExerciseDocument[] = [];
      for (const raw of raws) {
        const parsed = parseRecord('generatedExercises', raw);
        if (!parsed.ok) continue;
        const document = parsed.value;
        if (document.status !== 'active' || document.deletedAt !== null) continue;
        if (isFitGeneratedExercise(document.notionId, document.exercise)) documents.push(document);
      }
      return documents.sort((a, b) => a.createdAt - b.createdAt);
    },

    add({ notionId, exercises, model, promptVersion }) {
      return db.dexie.transaction('rw', [table, db.table('syncOutbox')], async () => {
        const now = clock.now();
        const stored: GeneratedExerciseDocument[] = [];
        for (const exercise of exercises) {
          // Checked again here: nothing unfit for local grading is ever stored (NO-05).
          if (!isFitGeneratedExercise(notionId, exercise)) continue;
          const document: GeneratedExerciseDocument = {
            id: crypto.randomUUID(),
            createdAt: now,
            updatedAt: now,
            deletedAt: null,
            schemaVersion: 1,
            notionId,
            step: STEP_OF_KIND[exercise.kind],
            exercise,
            model,
            promptVersion,
            status: 'active',
          };
          await writeRecord(db, 'generatedExercises', document, now);
          stored.push(document);
        }
        return stored;
      });
    },

    report(id) {
      return db.dexie.transaction('rw', [table, db.table('syncOutbox')], async () => {
        const raw: unknown = await table.get(id);
        if (raw === undefined) return;
        const parsed = parseRecord('generatedExercises', raw);
        if (!parsed.ok) return;
        const now = clock.now();
        await writeRecord(
          db,
          'generatedExercises',
          {
            ...parsed.value,
            status: 'reported',
            updatedAt: nextUpdatedAt(parsed.value.updatedAt, now),
          },
          now,
        );
      });
    },
  };
}
