/**
 * Exercises generated by the model on request (CUR-07, COST-09): stored once
 * validated, reused, never generated twice. A reported exercise is never
 * shown again, but kept.
 */
import { checkExercise, STEP_OF_KIND, type Exercise } from '../../domain/curriculum/exercise.ts';
import type { NotionId } from '../../domain/curriculum/notion-id.ts';
import type { Step } from '../../domain/curriculum/progress.ts';
import { nextUpdatedAt, type Clock } from '../../domain/primitives.ts';
import type { AppDatabase } from '../database.ts';
import { parseRecord, writeRecord } from '../records.ts';
import type { GeneratedExerciseDocument } from '../schemas/generated-exercises.ts';

export interface NewGeneratedExercises {
  readonly notionId: NotionId;
  readonly exercises: readonly Exercise[];
  readonly model: string;
  readonly promptVersion: string;
}

export interface GeneratedExerciseRepository {
  /** Active exercises of a notion and step, oldest first. */
  active(notionId: NotionId, step: Step): Promise<GeneratedExerciseDocument[]>;
  /** Stores the exercises fit for local grading; returns those stored. */
  add(batch: NewGeneratedExercises): Promise<GeneratedExerciseDocument[]>;
  /** The learner reports an exercise: it is never shown again. */
  report(id: string): Promise<void>;
}

export function createGeneratedExerciseRepository(
  db: AppDatabase,
  clock: Clock,
): GeneratedExerciseRepository {
  const table = db.table('generatedExercises');

  return {
    async active(notionId, step) {
      const raws: unknown[] = await table
        .where('[notionId+step]')
        .equals([notionId, step])
        .toArray();
      const documents: GeneratedExerciseDocument[] = [];
      for (const raw of raws) {
        const parsed = parseRecord('generatedExercises', raw);
        if (parsed.ok && parsed.value.status === 'active' && parsed.value.deletedAt === null) {
          documents.push(parsed.value);
        }
      }
      return documents.sort((a, b) => a.createdAt - b.createdAt);
    },

    add({ notionId, exercises, model, promptVersion }) {
      return db.dexie.transaction('rw', [table, db.table('syncOutbox')], async () => {
        const now = clock.now();
        const stored: GeneratedExerciseDocument[] = [];
        for (const exercise of exercises) {
          // Checked again here: nothing unfit for local grading is ever stored (NO-05).
          if (checkExercise(exercise).length > 0) continue;
          const document: GeneratedExerciseDocument = {
            id: crypto.randomUUID(),
            createdAt: now,
            updatedAt: now,
            deletedAt: null,
            schemaVersion: 1,
            notionId,
            step: STEP_OF_KIND[exercise.kind],
            exercise,
            model,
            promptVersion,
            status: 'active',
          };
          await writeRecord(db, 'generatedExercises', document, now);
          stored.push(document);
        }
        return stored;
      });
    },

    report(id) {
      return db.dexie.transaction('rw', [table, db.table('syncOutbox')], async () => {
        const raw: unknown = await table.get(id);
        if (raw === undefined) return;
        const parsed = parseRecord('generatedExercises', raw);
        if (!parsed.ok) return;
        const now = clock.now();
        await writeRecord(
          db,
          'generatedExercises',
          {
            ...parsed.value,
            status: 'reported',
            updatedAt: nextUpdatedAt(parsed.value.updatedAt, now),
          },
          now,
        );
      });
    },
  };
}
