-- Log of the AI calls (COST-05 to COST-08, docs/ARCHITECTURE.md §4.3 and §10).
--
-- Written only by the Edge Function "ai", with the secret key (role
-- service_role); the learner can read their own rows. No text of the learner
-- is ever stored here: identifiers, counters and codes only.

create table public.ai_calls (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  -- Generated by the client for each user action (idempotence).
  request_id uuid not null,
  -- 2 for the single new attempt after an invalid output (AI-07, D-016).
  attempt smallint not null default 1 check (attempt between 1 and 2),
  created_at timestamptz not null default now(),
  task text not null check (task ~ '^[a-z][a-z0-9-]{0,63}$'),
  model text not null check (char_length(model) between 1 and 100),
  prompt_version text not null check (char_length(prompt_version) between 1 and 100),
  status text not null check (
    status in (
      -- The call is running: its maximum cost is reserved.
      'reserved',
      'ok',
      'invalid_output',
      'truncated',
      'model_refusal',
      'error',
      -- Refused before any call: nothing was spent.
      'refused_budget',
      'refused_rate'
    )
  ),
  input_tokens integer check (input_tokens >= 0),
  output_tokens integer check (output_tokens >= 0),
  cache_creation_input_tokens integer check (cache_creation_input_tokens >= 0),
  cache_read_input_tokens integer check (cache_read_input_tokens >= 0),
  reserved_cost_usd numeric(10, 6) not null default 0 check (reserved_cost_usd >= 0),
  -- Actual cost, once the call is over.
  cost_usd numeric(10, 6) check (cost_usd >= 0),
  latency_ms integer check (latency_ms >= 0),
  error_code text check (char_length(error_code) <= 100),
  unique (user_id, request_id, attempt)
);

create index ai_calls_user_created on public.ai_calls (user_id, created_at);

alter table public.ai_calls enable row level security;

create policy "ai_calls: owner reads" on public.ai_calls
for select to authenticated using ((select auth.uid()) = user_id);

-- Explicit privileges (D-064). Only the Edge Function writes, with the
-- secret key; it is subject to no policy (service_role bypasses RLS).
revoke all on table public.ai_calls from anon, authenticated;
grant select on table public.ai_calls to authenticated;
grant select, insert, update on table public.ai_calls to service_role;

-- Spending counted against the cap: actual costs, and the reservation of the
-- calls still running (or interrupted without an actual cost, counted at
-- their maximum: the cap is never exceeded, D-016).
create function public.ai_spent_usd(p_user_id uuid, p_since timestamptz)
returns numeric
language sql
stable
security invoker
set search_path = ''
as $$
  select coalesce(sum(coalesce(c.cost_usd, c.reserved_cost_usd)), 0)
  from public.ai_calls as c
  where c.user_id = p_user_id and c.created_at >= p_since;
$$;

-- First instant of the current month, in UTC: the month of the cap.
create function public.ai_month_start()
returns timestamptz
language sql
stable
set search_path = ''
as $$
  select date_trunc('month', now() at time zone 'UTC') at time zone 'UTC';
$$;

-- ai_reserve_call: before any call to the model (docs/ARCHITECTURE.md §8).
--
-- In one transaction, and one at a time per user:
-- 1. a request identifier already received is refused (a double tap costs nothing);
-- 2. too many calls in the last minute are refused (COST-07);
-- 3. a call whose maximum cost would take the month over the cap is refused (COST-06);
-- 4. otherwise the maximum cost is reserved.
-- Checks 1 and 2 do not apply to the second attempt of a request, which
-- belongs to the same user action. Refusals are logged at no cost.
create function public.ai_reserve_call(
  p_user_id uuid,
  p_request_id uuid,
  p_attempt integer,
  p_task text,
  p_model text,
  p_prompt_version text,
  p_reserved_cost_usd numeric,
  p_monthly_budget_usd numeric,
  p_rate_limit_per_minute integer
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_used numeric;
  v_recent integer;
  v_call_id uuid;
begin
  perform pg_advisory_xact_lock(hashtextextended('ai_calls:' || p_user_id::text, 0));

  if p_attempt = 1 and exists (
    select 1 from public.ai_calls as c
    where c.user_id = p_user_id and c.request_id = p_request_id
  ) then
    return jsonb_build_object('outcome', 'duplicate');
  end if;

  v_used := public.ai_spent_usd(p_user_id, public.ai_month_start());

  if p_attempt = 1 then
    select count(*) into v_recent
    from public.ai_calls as c
    where c.user_id = p_user_id
      and c.created_at > now() - interval '1 minute'
      and c.status not in ('refused_budget', 'refused_rate');
    if v_recent >= p_rate_limit_per_minute then
      insert into public.ai_calls (user_id, request_id, attempt, task, model, prompt_version, status, cost_usd)
      values (p_user_id, p_request_id, p_attempt, p_task, p_model, p_prompt_version, 'refused_rate', 0);
      return jsonb_build_object('outcome', 'rate_limited', 'month_used_usd', v_used);
    end if;
  end if;

  if v_used + p_reserved_cost_usd > p_monthly_budget_usd then
    insert into public.ai_calls (user_id, request_id, attempt, task, model, prompt_version, status, cost_usd)
    values (p_user_id, p_request_id, p_attempt, p_task, p_model, p_prompt_version, 'refused_budget', 0);
    return jsonb_build_object('outcome', 'budget_exceeded', 'month_used_usd', v_used);
  end if;

  insert into public.ai_calls (
    user_id, request_id, attempt, task, model, prompt_version, status, reserved_cost_usd
  )
  values (
    p_user_id, p_request_id, p_attempt, p_task, p_model, p_prompt_version, 'reserved',
    p_reserved_cost_usd
  )
  returning id into v_call_id;

  return jsonb_build_object('outcome', 'reserved', 'call_id', v_call_id, 'month_used_usd', v_used);
end;
$$;

-- ai_complete_call: replaces the reservation by the outcome and the actual cost.
-- Returns false if the call was not (or no longer) reserved.
create function public.ai_complete_call(
  p_call_id uuid,
  p_status text,
  p_input_tokens integer,
  p_output_tokens integer,
  p_cache_creation_input_tokens integer,
  p_cache_read_input_tokens integer,
  p_cost_usd numeric,
  p_latency_ms integer,
  p_error_code text
)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if p_status not in ('ok', 'invalid_output', 'truncated', 'model_refusal', 'error') then
    raise exception 'ai_complete_call: % is not a final status', p_status using errcode = '22023';
  end if;
  update public.ai_calls
  set status = p_status,
    input_tokens = p_input_tokens,
    output_tokens = p_output_tokens,
    cache_creation_input_tokens = p_cache_creation_input_tokens,
    cache_read_input_tokens = p_cache_read_input_tokens,
    cost_usd = p_cost_usd,
    latency_ms = p_latency_ms,
    error_code = p_error_code
  where id = p_call_id and status = 'reserved';
  return found;
end;
$$;

-- ai_usage_summary: the "Consommation" screen (COST-08). "Today" is the day
-- in the learner's time zone (UTC if the name is unknown); the month is the
-- UTC month of the cap.
create function public.ai_usage_summary(p_user_id uuid, p_time_zone text)
returns jsonb
language plpgsql
stable
security invoker
set search_path = ''
as $$
declare
  v_zone text := 'UTC';
  v_month_start timestamptz := public.ai_month_start();
  v_day_start timestamptz;
begin
  if exists (select 1 from pg_catalog.pg_timezone_names as z where z.name = p_time_zone) then
    v_zone := p_time_zone;
  end if;
  v_day_start := date_trunc('day', now() at time zone v_zone) at time zone v_zone;

  return jsonb_build_object(
    'time_zone', v_zone,
    'month_start', (v_month_start at time zone 'UTC')::date,
    'resets_on', ((v_month_start at time zone 'UTC') + interval '1 month')::date,
    'month_usd', public.ai_spent_usd(p_user_id, v_month_start),
    'today_usd', public.ai_spent_usd(p_user_id, v_day_start),
    'by_task', coalesce(
      (
        select jsonb_agg(
          jsonb_build_object('task', t.task, 'calls', t.calls, 'cost_usd', t.cost_usd)
          order by t.task
        )
        from (
          select c.task,
            count(*) filter (where c.status not in ('refused_budget', 'refused_rate')) as calls,
            sum(coalesce(c.cost_usd, c.reserved_cost_usd)) as cost_usd
          from public.ai_calls as c
          where c.user_id = p_user_id and c.created_at >= v_month_start
          group by c.task
        ) as t
      ),
      '[]'::jsonb
    )
  );
end;
$$;

-- These functions take a user identifier: only the Edge Function may call them.
revoke execute on function public.ai_spent_usd(uuid, timestamptz) from public, anon, authenticated;
revoke execute on function public.ai_month_start() from public, anon, authenticated;
revoke execute on function public.ai_reserve_call(uuid, uuid, integer, text, text, text, numeric, numeric, integer) from public, anon, authenticated;
revoke execute on function public.ai_complete_call(uuid, text, integer, integer, integer, integer, numeric, integer, text) from public, anon, authenticated;
revoke execute on function public.ai_usage_summary(uuid, text) from public, anon, authenticated;
grant execute on function public.ai_spent_usd(uuid, timestamptz) to service_role;
grant execute on function public.ai_month_start() to service_role;
grant execute on function public.ai_reserve_call(uuid, uuid, integer, text, text, text, numeric, numeric, integer) to service_role;
grant execute on function public.ai_complete_call(uuid, text, integer, integer, integer, integer, numeric, integer, text) to service_role;
grant execute on function public.ai_usage_summary(uuid, text) to service_role;
