/**
 * Closed list of word families: the attested forms of one word (DECISIONS
 * D-058, D-072). Used only to check that a hint does not give an answer away
 * in another form ("meetings" for "meeting", "go" for "went").
 *
 * Every form is written out: no ending is ever removed or added by a rule, so
 * that two different words ("united" and "unit", "news" and "new") are never
 * related. A word missing from the list is only compared with itself.
 *
 * Spellings are the canonical ones of `spelling.ts` (American), since answers
 * are compared after that canonicalization ("travelled" is read "traveled").
 * A form may belong to several families ("left", "found", "lay"): two words are
 * related when they share a family, never through a third word.
 *
 * The verbs are also read by role (base, past…) in `verb-forms.ts` (D-088).
 */

/**
 * Irregular verbs: base, third person, past, past participle, -ing form; a
 * form equal to an earlier one is not repeated ("cut cuts cutting").
 */
export const IRREGULAR_VERBS = [
  'be am is are was were been being',
  'have has had having',
  'do does did done doing',
  'go goes went gone going',
  'make makes made making',
  'take takes took taken taking',
  'get gets got gotten getting',
  'give gives gave given giving',
  'come comes came coming',
  'see sees saw seen seeing',
  'know knows knew known knowing',
  'think thinks thought thinking',
  'tell tells told telling',
  'say says said saying',
  'find finds found finding',
  'leave leaves left leaving',
  'feel feels felt feeling',
  'keep keeps kept keeping',
  'bring brings brought bringing',
  'buy buys bought buying',
  'begin begins began begun beginning',
  'write writes wrote written writing',
  'speak speaks spoke spoken speaking',
  'send sends sent sending',
  'spend spends spent spending',
  'meet meets met meeting',
  'pay pays paid paying',
  'run runs ran running',
  'rise rises rose risen rising',
  'lend lends lent lending',
  'build builds built building',
  'hold holds held holding',
  'lead leads led leading',
  'lose loses lost losing',
  'win wins won winning',
  'sell sells sold selling',
  'stand stands stood standing',
  'understand understands understood understanding',
  'misunderstand misunderstands misunderstood misunderstanding',
  'teach teaches taught teaching',
  'catch catches caught catching',
  'choose chooses chose chosen choosing',
  'fall falls fell fallen falling',
  'grow grows grew grown growing',
  'drive drives drove driven driving',
  'become becomes became becoming',
  'break breaks broke broken breaking',
  'cost costs costing',
  'cut cuts cutting',
  'draw draws drew drawn drawing',
  'drink drinks drank drunk drinking',
  'eat eats ate eaten eating',
  'fly flies flew flown flying',
  'forget forgets forgot forgotten forgetting',
  'forgive forgives forgave forgiven forgiving',
  'hear hears heard hearing',
  'hide hides hid hidden hiding',
  'hit hits hitting',
  'hurt hurts hurting',
  'let lets letting',
  // "means" is left out: it is also a noun ("a means of payment").
  'mean meant meaning',
  'put puts putting',
  'read reads reading',
  'ride rides rode ridden riding',
  'ring rings rang rung ringing',
  'set sets setting',
  'shake shakes shook shaken shaking',
  'shoot shoots shot shooting',
  'show shows showed shown showing',
  'shut shuts shutting',
  'sing sings sang sung singing',
  'sink sinks sank sunk sinking',
  'sit sits sat sitting',
  'sleep sleeps slept sleeping',
  'spread spreads spreading',
  'steal steals stole stolen stealing',
  'stick sticks stuck sticking',
  'strike strikes struck striking',
  'swim swims swam swum swimming',
  'throw throws threw thrown throwing',
  'wake wakes woke woken waking',
  'wear wears wore worn wearing',
  'withdraw withdraws withdrew withdrawn withdrawing',
  'withhold withholds withheld withholding',
  'arise arises arose arisen arising',
  'bear bears bore borne bearing',
  'beat beats beaten beating',
  'bend bends bent bending',
  'bet bets betting',
  'bite bites bit bitten biting',
  'blow blows blew blown blowing',
  'broadcast broadcasts broadcasting',
  'burst bursts bursting',
  'deal deals dealt dealing',
  'dig digs dug digging',
  'feed feeds fed feeding',
  'fight fights fought fighting',
  'forbid forbids forbade forbidden forbidding',
  'forecast forecasts forecasting',
  'freeze freezes froze frozen freezing',
  'hang hangs hung hanging',
  'lay lays laid laying',
  'lie lies lay lain lying',
  'light lights lit lighting',
  'mislead misleads misled misleading',
  'overcome overcomes overcame overcoming',
  'oversee oversees oversaw overseen overseeing',
  'prove proves proved proven proving',
  'quit quits quitting',
  'rewrite rewrites rewrote rewritten rewriting',
  'seek seeks sought seeking',
  'shine shines shone shining',
  'shrink shrinks shrank shrunk shrinking',
  'split splits splitting',
  'swear swears swore sworn swearing',
  'sweep sweeps swept sweeping',
  'swing swings swung swinging',
  'tear tears tore torn tearing',
  'undergo undergoes underwent undergone undergoing',
  'undertake undertakes undertook undertaken undertaking',
  'upset upsets upsetting',
  'wind winds wound winding',
];

/** Modal verbs and their past or conditional forms. */
const MODALS = ['can cannot could', 'will would', 'shall should', 'may might'];

/** Regular verbs (several are also nouns: "report", "email", "offer"). */
export const REGULAR_VERBS = [
  'accept accepts accepted accepting',
  'agree agrees agreed agreeing',
  'allow allows allowed allowing',
  'analyze analyzes analyzed analyzing analyses',
  'answer answers answered answering',
  'appear appears appeared appearing',
  'apply applies applied applying',
  'approve approves approved approving',
  'arrange arranges arranged arranging',
  'arrive arrives arrived arriving',
  'ask asks asked asking',
  'attend attends attended attending',
  'belong belongs belonged belonging',
  'book books booked booking',
  'borrow borrows borrowed borrowing',
  'burn burns burned burning',
  'calculate calculates calculated calculating',
  'call calls called calling',
  'cancel cancels canceled canceling',
  'change changes changed changing',
  'check checks checked checking',
  'clean cleans cleaned cleaning',
  'close closes closed closing',
  'code codes coded coding',
  'collect collects collected collecting',
  'compare compares compared comparing',
  'complete completes completed completing',
  'confirm confirms confirmed confirming',
  'contact contacts contacted contacting',
  'cook cooks cooked cooking',
  'correct corrects corrected correcting',
  'crash crashes crashed crashing',
  'create creates created creating',
  'cross crosses crossed crossing',
  'debug debugs debugged debugging',
  'decide decides decided deciding',
  'decline declines declined declining',
  'decrease decreases decreased decreasing',
  'deliver delivers delivered delivering',
  'deploy deploys deployed deploying',
  'describe describes described describing',
  'design designs designed designing',
  'develop develops developed developing',
  'die dies died dying',
  'discuss discusses discussed discussing',
  'download downloads downloaded downloading',
  'dream dreams dreamed dreaming',
  'drop drops dropped dropping',
  'earn earns earned earning',
  'email emails emailed emailing',
  'end ends ended ending',
  'enjoy enjoys enjoyed enjoying',
  'estimate estimates estimated estimating',
  'exercise exercises exercised exercising',
  'expand expands expanded expanding',
  'expect expects expected expecting',
  'experience experiences experienced experiencing',
  'explain explains explained explaining',
  'fail fails failed failing',
  'fill fills filled filling',
  'finalize finalizes finalized finalizing',
  'finish finishes finished finishing',
  'fix fixes fixed fixing',
  'follow follows followed following',
  'grade grades graded grading',
  'graduate graduates graduated graduating',
  'guess guesses guessed guessing',
  'happen happens happened happening',
  'hate hates hated hating',
  'help helps helped helping',
  'hire hires hired hiring',
  'hope hopes hoped hoping',
  'improve improves improved improving',
  'include includes included including',
  'increase increases increased increasing',
  'install installs installed installing',
  'interview interviews interviewed interviewing',
  'introduce introduces introduced introducing',
  'invest invests invested investing',
  'invite invites invited inviting',
  'join joins joined joining',
  'land lands landed landing',
  'last lasts lasted lasting',
  'launch launches launched launching',
  'learn learns learned learning',
  'like likes liked liking',
  'listen listens listened listening',
  'live lives lived living',
  'log logs logged logging',
  'look looks looked looking',
  'love loves loved loving',
  'lower lowers lowered lowering',
  'manage manages managed managing',
  'mark marks marked marking',
  'mention mentions mentioned mentioning',
  'merge merges merged merging',
  'miss misses missed missing',
  'move moves moved moving',
  'need needs needed needing',
  'negotiate negotiates negotiated negotiating',
  'notice notices noticed noticing',
  'offer offers offered offering',
  'open opens opened opening',
  'order orders ordered ordering',
  'organize organizes organized organizing',
  'own owns owned owning',
  'pass passes passed passing',
  'phone phones phoned phoning',
  'pick picks picked picking',
  'plan plans planned planning',
  'play plays played playing',
  'post posts posted posting',
  'practice practices practise practises practiced practicing',
  'predict predicts predicted predicting',
  'prefer prefers preferred preferring',
  'prepare prepares prepared preparing',
  'present presents presented presenting',
  'print prints printed printing',
  'prioritize prioritizes prioritized prioritizing',
  'produce produces produced producing',
  'promise promises promised promising',
  'provide provides provided providing',
  'publish publishes published publishing',
  'push pushes pushed pushing',
  'rain rains rained raining',
  'raise raises raised raising',
  'reach reaches reached reaching',
  'realize realizes realized realizing',
  'receive receives received receiving',
  'recognize recognizes recognized recognizing',
  'recommend recommends recommended recommending',
  'recover recovers recovered recovering',
  'reduce reduces reduced reducing',
  'refuse refuses refused refusing',
  'release releases released releasing',
  'remain remains remained remaining',
  'remember remembers remembered remembering',
  'rent rents rented renting',
  'repair repairs repaired repairing',
  'reply replies replied replying',
  'report reports reported reporting',
  'require requires required requiring',
  'resign resigns resigned resigning',
  'restart restarts restarted restarting',
  'retire retires retired retiring',
  'return returns returned returning',
  'review reviews reviewed reviewing',
  'save saves saved saving',
  'schedule schedules scheduled scheduling',
  'seem seems seemed seeming',
  'serve serves served serving',
  'share shares shared sharing',
  'sign signs signed signing',
  'smile smiles smiled smiling',
  'snow snows snowed snowing',
  'solve solves solved solving',
  'spell spells spelled spelling',
  'start starts started starting',
  'stay stays stayed staying',
  'stop stops stopped stopping',
  'study studies studied studying',
  'submit submits submitted submitting',
  'succeed succeeds succeeded succeeding',
  'suggest suggests suggested suggesting',
  'summarize summarizes summarized summarizing',
  'support supports supported supporting',
  'switch switches switched switching',
  'talk talks talked talking',
  'test tests tested testing',
  'text texts texted texting',
  'thank thanks thanked thanking',
  'trade trades traded trading',
  'train trains trained training',
  'transfer transfers transferred transferring',
  'translate translates translated translating',
  'travel travels traveled traveling',
  'try tries tried trying',
  'turn turns turned turning',
  'type types typed typing',
  'unite unites united uniting',
  'update updates updated updating',
  'upload uploads uploaded uploading',
  'use uses used using',
  'visit visits visited visiting',
  'wait waits waited waiting',
  'walk walks walked walking',
  'want wants wanted wanting',
  'watch watches watched watching',
  'wish wishes wished wishing',
  'wonder wonders wondered wondering',
  'work works worked working',
  'worry worries worried worrying',
];

/** Nouns: singular and plural (nouns that are also verbs are listed above). */
const NOUNS = [
  'account accounts',
  'algorithm algorithms',
  'analysis analyses',
  'analyst analysts',
  'application applications',
  'article articles',
  'asset assets',
  'bank banks',
  'board boards',
  'bond bonds',
  'bonus bonuses',
  'boss bosses',
  'branch branches',
  'broker brokers',
  'budget budgets',
  'bug bugs',
  'candidate candidates',
  'car cars',
  'chart charts',
  'child children',
  'city cities',
  'class classes',
  'client clients',
  'colleague colleagues',
  'company companies',
  'contract contracts',
  'country countries',
  'course courses',
  'currency currencies',
  'customer customers',
  'dashboard dashboards',
  'database databases',
  'dataset datasets',
  'day days',
  'deadline deadlines',
  'degree degrees',
  'deposit deposits',
  'director directors',
  'document documents',
  'economy economies',
  'employee employees',
  'evening evenings',
  'exam exams',
  'family families',
  'feature features',
  'figure figures',
  'file files',
  'flight flights',
  'friend friends',
  'fund funds',
  'goal goals',
  'graph graphs',
  'holiday holidays',
  'hour hours',
  'house houses',
  'idea ideas',
  'internship internships',
  'investor investors',
  'invoice invoices',
  'job jobs',
  'language languages',
  'lesson lessons',
  'loan loans',
  'loss losses',
  'man men',
  'manager managers',
  'market markets',
  'meeting meetings',
  'message messages',
  'minute minutes',
  'model models',
  'month months',
  'morning mornings',
  'night nights',
  'number numbers',
  'office offices',
  'paper papers',
  'partner partners',
  'payment payments',
  'person people',
  'point points',
  'policy policies',
  'portfolio portfolios',
  'presentation presentations',
  'price prices',
  'problem problems',
  'product products',
  'profit profits',
  'project projects',
  'quarter quarters',
  'question questions',
  'rate rates',
  'recruiter recruiters',
  'result results',
  'revenue revenues',
  'risk risks',
  'salary salaries',
  'sale sales',
  'school schools',
  'sentence sentences',
  'server servers',
  'service services',
  'shareholder shareholders',
  'skill skills',
  'solution solutions',
  'step steps',
  'stock stocks',
  'student students',
  'supplier suppliers',
  'table tables',
  'task tasks',
  'tax taxes',
  'teacher teachers',
  'team teams',
  'ticket tickets',
  'trader traders',
  'unit units',
  'university universities',
  'user users',
  'vacation vacations',
  'version versions',
  'week weeks',
  'weekend weekends',
  'woman women',
  'word words',
  'year years',
];

/** Adjectives with their comparative and superlative forms. */
const ADJECTIVES = [
  'good better best',
  'bad worse worst',
  'big bigger biggest',
  'small smaller smallest',
  'high higher highest',
  'low lower lowest',
  'early earlier earliest',
  'late later latest',
  'long longer longest',
  'short shorter shortest',
  'fast faster fastest',
  'large larger largest',
  'cheap cheaper cheapest',
  'easy easier easiest',
  'hard harder hardest',
];

/** Every family, as the list of its forms. */
export const WORD_FAMILIES: readonly (readonly string[])[] = [
  ...IRREGULAR_VERBS,
  ...MODALS,
  ...REGULAR_VERBS,
  ...NOUNS,
  ...ADJECTIVES,
].map((forms) => forms.split(' '));
